version: "3.9"

services:
  nginx:
    image: nginx:latest
    container_name: nginx_proxy
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend/website/dist:/usr/share/nginx/html/website:ro
      - ./frontend/superadmin/dist:/usr/share/nginx/html/superadmin:ro
    depends_on:
      - digiplex-gateway
    networks:
      - digiplex-network
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"
    networks:
      - digiplex-network

  admin-service:
    build:
      context: .
      dockerfile: ./services/adminService/Dockerfile
    container_name: admin_service
    restart: always
    ports:
      - "3007:3007"
    depends_on:
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3007
      REDIS_URL: redis://redis:6379
    env_file:
      - ./services/adminService/.env
    networks:
      - digiplex-network

  auth-service:
    build:
      context: .
      dockerfile: ./services/authService/Dockerfile
    container_name: auth_service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3001
      REDIS_URL: redis://redis:6379
    env_file:
      - ./services/authService/.env
    networks:
      - digiplex-network

  key-management-service:
    build:
      context: .
      dockerfile: ./services/KeyManagementService/Dockerfile
    container_name: key_management_service
    restart: always
    ports:
      - "3008:3008"
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3008
    env_file:
      - ./services/KeyManagementService/.env
    networks:
      - digiplex-network

  user-service:
    build:
      context: .
      dockerfile: ./services/userService/Dockerfile
    container_name: user_service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3002
      REDIS_URL: redis://redis:6379
    env_file:
      - ./services/userService/.env
    networks:
      - digiplex-network

  subscription-service:
    build:
      context: .
      dockerfile: ./services/subscriptionService/Dockerfile
    container_name: subscription_service
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3003
      REDIS_URL: redis://redis:6379
    networks:
      - digiplex-network

  video-service:
    build:
      context: .
      dockerfile: ./services/videoService/Dockerfile
    container_name: video_service
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3004
      REDIS_URL: redis://redis:6379
    networks:
      - digiplex-network

  streaming-service:
    build:
      context: .
      dockerfile: ./services/streamingService/Dockerfile
    container_name: streaming_service
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3005
      REDIS_URL: redis://redis:6379
    networks:
      - digiplex-network

  upload-service:
    build:
      context: .
      dockerfile: ./services/uploadService/Dockerfile
    container_name: upload_service
    restart: always
    ports:
      - "3006:3006"
    depends_on:
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      REDIS_URL: redis://redis:6379
    env_file:
      - ./services/uploadService/.env
    networks:
      - digiplex-network

  video-worker:
    build:
      context: .
      dockerfile: ./services/uploadService/Dockerfile
    container_name: video_worker
    restart: always
    depends_on:
      redis:
        condition: service_started
    command: node dist/workers/videoWorker.js
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      REDIS_URL: redis://redis:6379
      IS_WORKER: "true"
    env_file:
      - ./services/uploadService/.env
    networks:
      - digiplex-network

  digiplex-gateway:
    build:
      context: ./digiplex_gateway
      dockerfile: Dockerfile
    container_name: digiplex_gateway
    restart: always
    # ports:
    #   - "80:8080"
    depends_on:
      admin-service:
        condition: service_started
      upload-service:
        condition: service_started
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      subscription-service:
        condition: service_started
      video-service:
        condition: service_started
      streaming-service:
        condition: service_started
    networks:
      - digiplex-network

volumes:
  postgres_data:

networks:
  digiplex-network:
    driver: bridge
