services:
  redis:
    image: redis:7
    container_name: redis_cache
    restart: always
    ports:
      - "6379:6379"

  # postgres:
  #   image: postgres:15
  #   container_name: postgres_db
  #   restart: always
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: digiiplex
  #   ports:
  #     - "5432:5432"
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   healthcheck:
  #     test: ["CMD-SHELL", "pg_isready -U postgres -d digiiplex"]
  #     interval: 5s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 10s

  admin-service:
    build:
      context: .
      dockerfile: ./services/adminService/Dockerfile
    container_name: admin_service
    restart: always
    ports:
      - "3007:3007"
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3007
      REDIS_URL: redis://redis:6379
    env_file:
      - ./services/adminService/.env

  auth-service:
    build:
      context: .
      dockerfile: ./services/authService/Dockerfile
    container_name: auth_service
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3001
      REDIS_URL: redis://redis:6379
    env_file:
      - ./services/authService/.env

  key-management-service:
    build:
      context: .
      dockerfile: ./services/KeyManagementService/Dockerfile
    container_name: key_management_service
    restart: always
    ports:
      - "3008:3008"
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3008
    env_file:
      - ./services/KeyManagementService/.env

  user-service:
    build:
      context: ./services/userService
      dockerfile: Dockerfile
    container_name: user_service
    restart: always
    ports:
      - "3002:3002"
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3002
      REDIS_URL: redis://redis:6379

  subscription-service:
    build:
      context: ./services/subscriptionService
      dockerfile: Dockerfile
    container_name: subscription_service
    restart: always
    ports:
      - "3003:3003"
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3003
      REDIS_URL: redis://redis:6379

  video-service:
    build:
      context: ./services/videoService
      dockerfile: Dockerfile
    container_name: video_service
    restart: always
    ports:
      - "3004:3004"
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3004
      REDIS_URL: redis://redis:6379

  streaming-service:
    build:
      context: ./services/streamingService
      dockerfile: Dockerfile
    container_name: streaming_service
    restart: always
    ports:
      - "3005:3005"
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      PORT: 3005
      REDIS_URL: redis://redis:6379

  digiplex-gateway:
    build:
      context: ./digiplex_gateway
      dockerfile: Dockerfile
    container_name: digiplex_gateway
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      admin-service:
        condition: service_started
      upload-service:
        condition: service_started
      auth-service:
        condition: service_started
      user-service:
        condition: service_started
      subscription-service:
        condition: service_started
      video-service:
        condition: service_started
      streaming-service:
        condition: service_started

  upload-service:
    build:
      context: ./services/uploadService
      dockerfile: Dockerfile
    container_name: upload_service
    restart: always
    ports:
      - "3006:3006"
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_started
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      REDIS_URL: redis://redis:6379
    env_file:
      - ./services/uploadService/.env

  video-worker:
    build:
      context: ./services/uploadService
      dockerfile: Dockerfile
    container_name: video_worker
    restart: always
    depends_on:
      # postgres:
      #   condition: service_healthy
      redis:
        condition: service_started
    command: node dist/workers/videoWorker.js
    environment:
      DATABASE_URL: postgresql://postgres.zydvwzxuybmfinntmntn:yJ7NFtewqL6IRLfN@aws-1-ap-south-1.pooler.supabase.com:6543/postgres
      REDIS_URL: redis://redis:6379
      IS_WORKER: "true"
    env_file:
      - ./services/uploadService/.env

volumes:
  postgres_data:
