services:
  gateway:
    build: ./digiplex_gateway
    ports:
      - "8080:8080"
    depends_on:
      - admin
      - upload

  admin:
    build: ./services/adminService
    ports:
      - "3007:3007"
    env_file:
      - ./services/adminService/.env

  upload:
    build: ./services/uploadService
    ports:
      - "3006:3006"
    env_file:
      - ./services/uploadService/.env