http:
  port: 8080
admin:
  port: 9876
  host: localhost
apiEndpoints:
  users:
    paths: '/users/*'
  admin:
    paths: '/admin/*'
serviceEndpoints:
  userService:
    url: 'http://127.0.0.1:3001'
  adminService:
    url: 'http://127.0.0.1:3007'
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - users
    policies:
      - proxy:
          - action:
              serviceEndpoint: userService 
              changeOrigin: true
  
  adminPipeline:
    apiEndpoints:
      - admin
    policies:
      - proxy:
          - action:
              serviceEndpoint: adminService 
              changeOrigin: true
