http:
  port: 8080

admin:
  port: 9876
  host: localhost

apiEndpoints:
  admin:
    paths: '/admin/*'
  upload:
    paths: '/upload/*'

serviceEndpoints:
  adminService:
    url: 'http://127.0.0.1:3007'
  uploadService:
    url: 'http://127.0.0.1:3006'

policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit

pipelines:
  adminPipeline:
    apiEndpoints:
      - admin
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,HEAD,PUT,PATCH,POST,DELETE"
              allowedHeaders: "Content-Type, Authorization"
      - proxy:
          - action:
              serviceEndpoint: adminService
              changeOrigin: true

  uploadPipeline:
    apiEndpoints:
      - upload
    policies:
      - cors:
          - action:
              origin: "*"
              methods: "GET,HEAD,PUT,PATCH,POST,DELETE"
              allowedHeaders: "Content-Type, Authorization"
      - proxy:
          - action:
              serviceEndpoint: uploadService
              changeOrigin: true