events {}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    server {
        listen 80;

        # Website frontend
        location /website/ {
            alias /usr/share/nginx/html/website/;
            index index.html;
            try_files $uri $uri/ /website/index.html;
        }

        # Superadmin frontend
        location /superadmin/ {
            alias /usr/share/nginx/html/superadmin/;
            index index.html;
            try_files $uri $uri/ /superadmin/index.html;
        }

        # Admin frontend
        location /admin/ {
            alias /usr/share/nginx/html/admin/;
            index index.html;
            try_files $uri $uri/ /admin/index.html;
        }

        # creator frontend
        location /creator/ {
            alias /usr/share/nginx/html/creator/;
            index index.html;
            try_files $uri $uri/ /creator/index.html;
        }

        # API Gateway
        location /api/ {
            proxy_pass http://digiplex_gateway:8080/;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
        }
    }
}